apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: tenantguard-aws-secrets
spec:
  provider: aws
  parameters:
    usePodIdentity: "true"
    objects: |
      - objectName: "tenantguard-prod/database"
        objectType: "secretsmanager"
        jmesPath:
          - path: "url"
            objectAlias: "spring.datasource.url"
      - objectName: "${RDS_MASTER_SECRET_ARN}"
        objectType: "secretsmanager"
        jmesPath:
          - path: "username"
            objectAlias: "spring.datasource.username"
          - path: "password"
            objectAlias: "spring.datasource.password"
      - objectName: "tenantguard-prod/redis"
        objectType: "secretsmanager"
        jmesPath:
          - path: "host"
            objectAlias: "spring.data.redis.host"
          - path: "port"
            objectAlias: "spring.data.redis.port"
          - path: "tls"
            objectAlias: "spring.data.redis.ssl.enabled"
