apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: tenantguard-aws-secrets
spec:
  provider: aws
  parameters:
    usePodIdentity: "true"
    objects: |
      - objectName: "tenantguard-prod/database"
        objectType: "secretsmanager"
        jmesPath:
          - path: "host"
            objectAlias: "db-host"
          - path: "port"
            objectAlias: "db-port"
          - path: "database"
            objectAlias: "db-name"
          - path: "username"
            objectAlias: "db-username"
          - path: "password"
            objectAlias: "db-password"
      - objectName: "tenantguard-prod/redis"
        objectType: "secretsmanager"
        jmesPath:
          - path: "host"
            objectAlias: "redis-host"
          - path: "port"
            objectAlias: "redis-port"
